// Daily Ops SOP — merge + normalization helpers.
//
// The Daily Ops SOP (operator.dailyOps) is an operator/coach-authored
// standing daily routine. It is DISTINCT from the per-day DailyOpsPlan
// schedule generated by Gunny's <daily_ops_json> channel — this is one
// persistent, hand-authored document that lives on the operator record.
//
// Writes go through PATCH /api/operators/:id/daily-ops (and the MCP
// set_daily_ops / set_client_daily_ops tools), both of which call
// mergeDailyOps so the deep-merge + version bump + updatedAt stamp
// happen in exactly one place. Only the fields a caller passes change;
// everything else is preserved. Nested objects (trainingVariants,
// phase) merge one level deep; the array fields (anchors,
// supplementSchedule, sleepProtocol) replace wholesale when supplied
// (a partial array merge has no well-defined identity to merge on).

import type { DailyOpsSOP } from './types';

/** A write patch — any subset of the SOP minus the server-owned
 *  bookkeeping fields, which mergeDailyOps always sets itself. */
export type DailyOpsPatch = Partial<Omit<DailyOpsSOP, 'version' | 'updatedAt'>>;

/** True when the stored value is an empty/unset SOP ({} default). */
export function isEmptyDailyOps(raw: unknown): boolean {
  if (!raw || typeof raw !== 'object') return true;
  const obj = raw as Record<string, unknown>;
  // A real SOP always carries a version (set on first write).
  return typeof obj.version !== 'number';
}

/** Coerce a raw JSON value (the Prisma column) into a DailyOpsSOP, or
 *  null when it has never been written. */
export function readDailyOps(raw: unknown): DailyOpsSOP | null {
  if (isEmptyDailyOps(raw)) return null;
  return raw as DailyOpsSOP;
}

function isPlainObject(v: unknown): v is Record<string, unknown> {
  return !!v && typeof v === 'object' && !Array.isArray(v);
}

/**
 * Deep-merge a patch into the existing SOP, bumping `version` and
 * stamping `updatedAt`. Pure — does not mutate its inputs.
 *
 * @param existingRaw  the current operator.dailyOps JSON ({} when unset)
 * @param patch        the fields to change
 * @param opts.authoredBy  who authored this write ("gunny" | "operator");
 *                         falls back to the existing author, then "operator"
 * @param opts.now     ISO timestamp override (tests)
 */
export function mergeDailyOps(
  existingRaw: unknown,
  patch: DailyOpsPatch,
  opts: { authoredBy?: string; now?: string } = {},
): DailyOpsSOP {
  const existing = isPlainObject(existingRaw) ? existingRaw : {};
  const prevVersion = typeof existing.version === 'number' ? (existing.version as number) : 0;

  const merged: Record<string, unknown> = { ...existing };

  // Scalar + array fields: replace when supplied, preserve otherwise.
  if (patch.markdown !== undefined) merged.markdown = patch.markdown;
  if (patch.authoredBy !== undefined) merged.authoredBy = patch.authoredBy;
  if (patch.anchors !== undefined) merged.anchors = patch.anchors;
  if (patch.supplementSchedule !== undefined) merged.supplementSchedule = patch.supplementSchedule;
  if (patch.sleepProtocol !== undefined) merged.sleepProtocol = patch.sleepProtocol;

  // Nested objects: shallow-merge one level so callers can patch just
  // `phase.label` or `trainingVariants.am` without dropping the rest.
  if (patch.trainingVariants !== undefined) {
    const prev = isPlainObject(existing.trainingVariants) ? existing.trainingVariants : {};
    merged.trainingVariants = { ...prev, ...patch.trainingVariants };
  }
  if (patch.phase !== undefined) {
    const prev = isPlainObject(existing.phase) ? existing.phase : {};
    merged.phase = { ...prev, ...patch.phase };
  }

  // Server-owned bookkeeping — always set, never trusted from the caller.
  merged.version = prevVersion + 1;
  merged.updatedAt = opts.now ?? new Date().toISOString();
  if (opts.authoredBy) {
    merged.authoredBy = opts.authoredBy;
  } else if (typeof merged.authoredBy !== 'string') {
    merged.authoredBy = 'operator';
  }
  // markdown is the render source-of-truth — guarantee it's a string so
  // the UI never has to null-check it.
  if (typeof merged.markdown !== 'string') merged.markdown = '';

  return merged as unknown as DailyOpsSOP;
}
