'use client';

// Daily Ops — Gunny's prescribed daily-schedule planner.
//
// Sister surface to the Workout Planner. Owns the rhythm of the day —
// wake / sun / caffeine / meals / supps / workout window / wind-down /
// sleep — fully personalized using corpus knowledge (hypertrophy
// supplement stack, natural T optimization protocol, periodization
// phase, junior policies, life stage). Plans are generated by Gunny
// via the `<daily_ops_json>` channel — this surface is read-only +
// feedback, NOT a builder.
//
// Styling: matches the existing GUNS UP design system (.btn classes
// from design-system.css + inline styles using the CSS vars). The
// initial Phase 1 cut was written with Tailwind utility classes which
// silently no-op'd in this project (Tailwind is NOT installed) — every
// button rendered as the iOS Safari default white pill. Rewrite here
// uses .btn / .btn-amber / inline tactical chrome to match
// ParentDashboard / Planner / IntelCenter styling.

import React, { useEffect, useMemo, useState, useCallback } from 'react';
import { useLanguage } from '@/lib/i18n';
import { Operator } from '@/lib/types';
import { hasCommanderAccess } from '@/lib/tierGates';
import { getLocalDateStr } from '@/lib/dateUtils';
import {
  ensurePushSubscription,
  getPushPermissionState,
  unsubscribePush,
  type PushPermission,
} from '@/lib/pushClient';
import type {
  DailyOpsPlanShape,
  DailyBlock,
  BlockCategory,
  BlockFeedback,
} from '@/lib/dailyOpsTypes';

interface DailyOpsProps {
  operator: Operator;
  onSendGunnyMessage?: (prompt: string) => void;
}

interface RhythmShape {
  blockSkipRates?: Record<string, number>;
  feedbackSampleCount?: number;
}

const HIGH_SKIP_THRESHOLD = 0.6;

// Category accent colors, drawn from the existing palette.
const CATEGORY_TINT: Record<BlockCategory, string> = {
  wake:                  '#ffd966',
  sun_exposure:          '#ffe9a8',
  caffeine_window_open:  '#ffa14d',
  caffeine_cutoff:       '#ffa14d',
  meal:                  '#ff8c00',
  pre_workout_supp:      '#5fdf8a',
  workout:               '#ff5252',
  post_workout:          '#5fdf8a',
  mobility:              '#7fdfff',
  wind_down:             '#c79bff',
  pre_bed_supp:          '#c79bff',
  sleep_target:          '#9faaff',
  sauna:                 '#ff7a92',
  cold_exposure:         '#9bd9ff',
  recovery_walk:         '#7fe0d0',
  fifa_warmup:           '#5fdf8a',
  mistake_reset_ritual:  '#ff7adf',
};
const CATEGORY_LABEL: Record<BlockCategory, string> = {
  wake: 'WAKE',
  sun_exposure: 'SUN',
  caffeine_window_open: 'CAFFEINE',
  caffeine_cutoff: 'CAFF CUTOFF',
  meal: 'MEAL',
  pre_workout_supp: 'PRE-WO SUPP',
  workout: 'WORKOUT',
  post_workout: 'POST-WO',
  mobility: 'MOBILITY',
  wind_down: 'WIND DOWN',
  pre_bed_supp: 'PRE-BED SUPP',
  sleep_target: 'SLEEP',
  sauna: 'SAUNA',
  cold_exposure: 'COLD',
  recovery_walk: 'WALK',
  fifa_warmup: 'FIFA 11+',
  mistake_reset_ritual: 'RESET',
};
function categoryTint(c: BlockCategory): string {
  return CATEGORY_TINT[c] ?? '#a0a0a0';
}
function categoryLabel(c: BlockCategory): string {
  return CATEGORY_LABEL[c] ?? 'BLOCK';
}

function sortBlocks(blocks: DailyBlock[]): DailyBlock[] {
  return [...blocks].sort((a, b) => a.startTime.localeCompare(b.startTime));
}

function dateOffsetISO(daysOffset: number): string {
  const d = new Date();
  d.setDate(d.getDate() + daysOffset);
  return d.toISOString().slice(0, 10);
}

const STATUS_COPY: Record<DailyOpsPlanShape['status'], string> = {
  active: 'ACTIVE',
  pending_parent_approval: 'AWAITING PARENT APPROVAL',
  approved: 'APPROVED',
  rejected: 'REJECTED — REQUEST A NEW PLAN',
};
const STATUS_COLOR: Record<DailyOpsPlanShape['status'], string> = {
  active: '#00ff41',
  approved: '#00ff41',
  pending_parent_approval: '#ff8c00',
  rejected: '#ff4040',
};

// ---------------------------------------------------------------------------
// Style primitives — keep all inline-style objects scoped near the JSX.
// ---------------------------------------------------------------------------

const styles = {
  page: {
    padding: '14px 14px 24px',
    maxWidth: 720,
    margin: '0 auto',
    fontFamily: "'Share Tech Mono', monospace",
  } as React.CSSProperties,
  pageWide: {
    padding: '14px 14px 24px',
    maxWidth: 1100,
    margin: '0 auto',
    fontFamily: "'Share Tech Mono', monospace",
  } as React.CSSProperties,
  headerRow: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
    flexWrap: 'wrap',
    marginBottom: 14,
  } as React.CSSProperties,
  title: {
    color: '#ff8c00',
    fontFamily: 'Orbitron, sans-serif',
    fontSize: 18,
    fontWeight: 700,
    letterSpacing: 3,
    margin: 0,
  } as React.CSSProperties,
  dateChip: {
    fontFamily: "'Share Tech Mono', monospace",
    fontSize: 11,
    color: '#888',
    letterSpacing: 1,
  } as React.CSSProperties,
  segmented: {
    display: 'inline-flex',
    border: '1px solid #1a1a1a',
    borderRadius: 3,
    overflow: 'hidden',
  } as React.CSSProperties,
  segBtn: (active: boolean): React.CSSProperties => ({
    appearance: 'none',
    WebkitAppearance: 'none',
    background: active ? '#ff8c00' : '#0a0a0a',
    color: active ? '#0a0a0a' : '#888',
    border: 'none',
    fontFamily: 'Orbitron, sans-serif',
    fontSize: 10,
    fontWeight: 700,
    letterSpacing: 2,
    padding: '6px 10px',
    cursor: 'pointer',
    minHeight: 32,
  }),
  bell: (state: PushPermission): React.CSSProperties => ({
    appearance: 'none',
    WebkitAppearance: 'none',
    display: 'inline-flex',
    alignItems: 'center',
    gap: 4,
    padding: '6px 8px',
    background: '#0a0a0a',
    border: `1px solid ${
      state === 'granted'
        ? 'rgba(0, 255, 65, 0.4)'
        : state === 'denied'
          ? 'rgba(255, 64, 64, 0.4)'
          : '#2a2a2a'
    }`,
    color:
      state === 'granted' ? '#00ff41' : state === 'denied' ? '#ff4040' : '#888',
    fontFamily: 'Orbitron, sans-serif',
    fontSize: 9,
    fontWeight: 700,
    letterSpacing: 1.5,
    borderRadius: 3,
    cursor: 'pointer',
    minHeight: 32,
  }),
  emptyCard: {
    background: '#0a0a0a',
    border: '1px solid #1a1a1a',
    borderRadius: 4,
    padding: 18,
    textAlign: 'center' as const,
    fontSize: 12,
    color: '#a0a0a0',
  } as React.CSSProperties,
  errorBox: {
    background: 'rgba(255, 64, 64, 0.08)',
    border: '1px solid rgba(255, 64, 64, 0.35)',
    borderRadius: 3,
    padding: 10,
    color: '#ffb3b3',
    fontSize: 12,
    marginBottom: 12,
  } as React.CSSProperties,
  upgradeCard: {
    background: '#0a0a0a',
    border: '1px solid rgba(255, 140, 0, 0.35)',
    borderRadius: 4,
    padding: 18,
  } as React.CSSProperties,
  statusRow: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 10,
    fontSize: 10,
    letterSpacing: 2,
    color: '#888',
    fontFamily: 'Orbitron, sans-serif',
    fontWeight: 700,
  } as React.CSSProperties,
  reshapeLink: {
    appearance: 'none',
    WebkitAppearance: 'none',
    background: 'transparent',
    border: 'none',
    color: '#888',
    fontFamily: 'Orbitron, sans-serif',
    fontSize: 10,
    letterSpacing: 1.5,
    cursor: 'pointer',
    textDecoration: 'underline',
    textUnderlineOffset: 2,
    padding: 0,
  } as React.CSSProperties,
  notesCallout: {
    borderLeft: '2px solid rgba(255, 140, 0, 0.35)',
    background: 'rgba(255, 140, 0, 0.06)',
    color: 'rgba(255, 217, 168, 0.9)',
    fontStyle: 'italic',
    fontSize: 11.5,
    padding: '8px 10px',
    marginBottom: 14,
    lineHeight: 1.5,
  } as React.CSSProperties,
  juniorPending: {
    background: 'rgba(255, 140, 0, 0.08)',
    border: '1px solid rgba(255, 140, 0, 0.35)',
    borderRadius: 3,
    padding: 10,
    color: '#ffd9a8',
    fontSize: 11.5,
    marginBottom: 12,
    lineHeight: 1.5,
  } as React.CSSProperties,
  juniorRejected: {
    background: 'rgba(255, 64, 64, 0.08)',
    border: '1px solid rgba(255, 64, 64, 0.35)',
    borderRadius: 3,
    padding: 10,
    color: '#ffb3b3',
    fontSize: 11.5,
    marginBottom: 12,
    lineHeight: 1.5,
  } as React.CSSProperties,
  blockRow: (tint: string, dimmed: boolean): React.CSSProperties => ({
    display: 'grid',
    gridTemplateColumns: '64px 1fr',
    gap: 10,
    padding: '10px 0 10px 12px',
    borderLeft: `2px solid ${tint}40`,
    opacity: dimmed ? 0.45 : 1,
  }),
  blockTime: {
    fontFamily: "'Share Tech Mono', monospace",
    fontSize: 13,
    color: '#e0e0e0',
    fontWeight: 600,
  } as React.CSSProperties,
  blockEnd: {
    fontFamily: "'Share Tech Mono', monospace",
    fontSize: 10,
    color: '#666',
    marginTop: 2,
  } as React.CSSProperties,
  blockHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    flexWrap: 'wrap',
    marginBottom: 2,
  } as React.CSSProperties,
  catLabel: (tint: string): React.CSSProperties => ({
    color: tint,
    fontFamily: 'Orbitron, sans-serif',
    fontSize: 9.5,
    fontWeight: 700,
    letterSpacing: 1.5,
  }),
  flexTag: {
    color: '#666',
    fontFamily: "'Share Tech Mono', monospace",
    fontSize: 9,
  } as React.CSSProperties,
  pillTag: (color: string, bg: string): React.CSSProperties => ({
    color,
    background: bg,
    border: `1px solid ${color}40`,
    fontFamily: 'Orbitron, sans-serif',
    fontSize: 8.5,
    fontWeight: 700,
    letterSpacing: 1,
    padding: '1px 6px',
    borderRadius: 2,
  }),
  blockLabel: {
    color: '#e0e0e0',
    fontSize: 13,
    fontWeight: 500,
  } as React.CSSProperties,
  blockRationale: {
    color: '#888',
    fontSize: 11,
    fontStyle: 'italic',
    lineHeight: 1.4,
    marginTop: 2,
  } as React.CSSProperties,
  feedbackRow: {
    display: 'flex',
    gap: 6,
    marginTop: 8,
    flexWrap: 'wrap',
  } as React.CSSProperties,
  feedbackBtn: (
    active: boolean,
    activeBg: string,
    activeBorder: string,
    activeColor: string,
  ): React.CSSProperties => ({
    appearance: 'none',
    WebkitAppearance: 'none',
    background: active ? activeBg : '#0a0a0a',
    border: `1px solid ${active ? activeBorder : '#2a2a2a'}`,
    color: active ? activeColor : '#888',
    fontFamily: 'Orbitron, sans-serif',
    fontSize: 9,
    fontWeight: 700,
    letterSpacing: 1.5,
    padding: '4px 8px',
    borderRadius: 2,
    cursor: 'pointer',
    minHeight: 28,
  }),
  footer: {
    marginTop: 22,
    paddingTop: 14,
    borderTop: '1px solid #1a1a1a',
    textAlign: 'center' as const,
  } as React.CSSProperties,
  footerNote: {
    color: '#666',
    fontSize: 10,
    fontStyle: 'italic',
    margin: 0,
    marginBottom: 8,
  } as React.CSSProperties,
  weekGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(7, 1fr)',
    gap: 4,
  } as React.CSSProperties,
  weekDay: (today: boolean): React.CSSProperties => ({
    border: `1px solid ${today ? 'rgba(255, 140, 0, 0.5)' : '#1a1a1a'}`,
    background: today ? 'rgba(255, 140, 0, 0.06)' : '#0a0a0a',
    borderRadius: 3,
    padding: 6,
    minHeight: 180,
  }),
  weekDayLabel: (today: boolean): React.CSSProperties => ({
    fontFamily: 'Orbitron, sans-serif',
    fontSize: 9,
    fontWeight: 700,
    letterSpacing: 2,
    color: today ? '#ff8c00' : '#666',
    textAlign: 'center',
    marginBottom: 2,
  }),
  weekDayDate: {
    fontFamily: "'Share Tech Mono', monospace",
    fontSize: 9,
    color: '#555',
    textAlign: 'center' as const,
    marginBottom: 6,
  } as React.CSSProperties,
  weekChip: (tint: string, dimmed: boolean): React.CSSProperties => ({
    display: 'grid',
    gridTemplateColumns: '36px 1fr',
    gap: 4,
    fontSize: 10,
    padding: '2px 0',
    opacity: dimmed ? 0.45 : 1,
  }),
  weekChipTime: {
    color: '#666',
    fontFamily: "'Share Tech Mono', monospace",
    fontSize: 9,
  } as React.CSSProperties,
  weekChipCat: (tint: string): React.CSSProperties => ({
    color: tint,
    fontFamily: 'Orbitron, sans-serif',
    fontSize: 9,
    fontWeight: 700,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  }),
  weekPipsRow: {
    display: 'flex',
    gap: 2,
    justifyContent: 'center',
    marginBottom: 6,
  } as React.CSSProperties,
  weekPip: (color: string): React.CSSProperties => ({
    width: 5,
    height: 5,
    borderRadius: '50%',
    background: color,
  }),
  weekLegend: {
    color: '#555',
    fontSize: 10,
    fontStyle: 'italic' as const,
    textAlign: 'center' as const,
    marginTop: 10,
  } as React.CSSProperties,
};

// ---------------------------------------------------------------------------
// BlockCard
// ---------------------------------------------------------------------------

interface BlockCardProps {
  block: DailyBlock;
  feedback: BlockFeedback | undefined;
  onFeedback: (followed: BlockFeedback['followed']) => void;
  disabled: boolean;
  skipRate?: number;
}

const BlockCard: React.FC<BlockCardProps> = ({
  block,
  feedback,
  onFeedback,
  disabled,
  skipRate,
}) => {
  const tint = categoryTint(block.category);
  const followed = feedback?.followed;
  const dimmed = (skipRate ?? 0) >= HIGH_SKIP_THRESHOLD;
  const isUserOverride = block.source === 'user_override';

  return (
    <div style={styles.blockRow(tint, dimmed)}>
      <div>
        <div style={styles.blockTime}>{block.startTime}</div>
        {block.endTime && <div style={styles.blockEnd}>→ {block.endTime}</div>}
      </div>
      <div>
        <div style={styles.blockHeader}>
          <span style={styles.catLabel(tint)}>{categoryLabel(block.category)}</span>
          {block.flexibility !== 'fixed' && (
            <span style={styles.flexTag}>
              ±{block.flexibility === 'flex_30' ? '30m' : '2h'}
            </span>
          )}
          {isUserOverride && (
            <span style={styles.pillTag('#ff8c00', 'rgba(255, 140, 0, 0.1)')}>
              YOU MOVED THIS
            </span>
          )}
          {dimmed && (
            <span style={styles.pillTag('#888', 'rgba(255,255,255,0.04)')}>
              OFTEN SKIPPED
            </span>
          )}
        </div>
        <div style={styles.blockLabel}>{block.label}</div>
        <div style={styles.blockRationale}>{block.rationale}</div>
        {!disabled && (
          <div style={styles.feedbackRow}>
            <button
              type="button"
              onClick={() => onFeedback('yes')}
              style={styles.feedbackBtn(
                followed === 'yes',
                'rgba(0, 255, 65, 0.15)',
                '#00ff41',
                '#00ff41',
              )}
            >
              ✓ ON TIME
            </button>
            <button
              type="button"
              onClick={() => onFeedback('partial')}
              style={styles.feedbackBtn(
                followed === 'partial',
                'rgba(255, 140, 0, 0.15)',
                '#ff8c00',
                '#ff8c00',
              )}
            >
              ~ SHIFTED
            </button>
            <button
              type="button"
              onClick={() => onFeedback('no')}
              style={styles.feedbackBtn(
                followed === 'no',
                'rgba(255, 64, 64, 0.15)',
                '#ff4040',
                '#ff4040',
              )}
            >
              ✗ SKIPPED
            </button>
          </div>
        )}
      </div>
    </div>
  );
};

// ---------------------------------------------------------------------------
// WeekView
// ---------------------------------------------------------------------------

interface WeekViewProps {
  plans: DailyOpsPlanShape[];
  rhythm: RhythmShape | null;
  todayISO: string;
}
function dayLabel(iso: string, todayISO: string): string {
  if (iso === todayISO) return 'TODAY';
  return new Date(iso + 'T00:00:00')
    .toLocaleDateString(undefined, { weekday: 'short' })
    .toUpperCase();
}
function adherenceSummary(plan: DailyOpsPlanShape | undefined): {
  yes: number;
  partial: number;
  no: number;
  total: number;
} {
  if (!plan) return { yes: 0, partial: 0, no: 0, total: 0 };
  let yes = 0;
  let partial = 0;
  let no = 0;
  for (const fb of Object.values(plan.feedback ?? {})) {
    if (fb.followed === 'yes') yes++;
    else if (fb.followed === 'partial') partial++;
    else if (fb.followed === 'no') no++;
  }
  return { yes, partial, no, total: yes + partial + no };
}

const WeekView: React.FC<WeekViewProps> = ({ plans, rhythm, todayISO }) => {
  const days: { iso: string; plan: DailyOpsPlanShape | undefined }[] = [];
  for (let i = 6; i >= 0; i--) {
    const iso = dateOffsetISO(-i);
    days.push({ iso, plan: plans.find((p) => p.date === iso) });
  }
  return (
    <div style={styles.weekGrid}>
      {days.map(({ iso, plan }) => {
        const isToday = iso === todayISO;
        const adherence = adherenceSummary(plan);
        const sortedBlocks = plan ? sortBlocks(plan.blocks) : [];
        return (
          <div key={iso} style={styles.weekDay(isToday)}>
            <div style={styles.weekDayLabel(isToday)}>{dayLabel(iso, todayISO)}</div>
            <div style={styles.weekDayDate}>{iso.slice(5)}</div>
            {!plan && (
              <div
                style={{
                  fontSize: 10,
                  color: '#444',
                  fontStyle: 'italic',
                  textAlign: 'center',
                  paddingTop: 6,
                }}
              >
                no plan
              </div>
            )}
            {plan && (
              <>
                {adherence.total > 0 && (
                  <div style={styles.weekPipsRow}>
                    {Array.from({ length: adherence.yes }).map((_, i) => (
                      <span key={`y${i}`} style={styles.weekPip('#00ff41')} />
                    ))}
                    {Array.from({ length: adherence.partial }).map((_, i) => (
                      <span key={`p${i}`} style={styles.weekPip('#ff8c00')} />
                    ))}
                    {Array.from({ length: adherence.no }).map((_, i) => (
                      <span key={`n${i}`} style={styles.weekPip('#ff4040')} />
                    ))}
                  </div>
                )}
                {sortedBlocks.map((b) => {
                  const tint = categoryTint(b.category);
                  const skipRate = rhythm?.blockSkipRates?.[b.category] ?? 0;
                  const dimmed = skipRate >= HIGH_SKIP_THRESHOLD;
                  return (
                    <div
                      key={b.id}
                      style={styles.weekChip(tint, dimmed)}
                      title={`${b.label}${b.rationale ? ' — ' + b.rationale : ''}`}
                    >
                      <span style={styles.weekChipTime}>{b.startTime}</span>
                      <span style={styles.weekChipCat(tint)}>
                        {categoryLabel(b.category)}
                      </span>
                    </div>
                  );
                })}
              </>
            )}
          </div>
        );
      })}
    </div>
  );
};

// ---------------------------------------------------------------------------
// Main DailyOps surface
// ---------------------------------------------------------------------------

type ViewMode = 'today' | 'week';

const DailyOps: React.FC<DailyOpsProps> = ({ operator, onSendGunnyMessage }) => {
  const { t } = useLanguage();
  const [mode, setMode] = useState<ViewMode>('today');
  const [plan, setPlan] = useState<DailyOpsPlanShape | null>(null);
  const [weekPlans, setWeekPlans] = useState<DailyOpsPlanShape[]>([]);
  const [rhythm, setRhythm] = useState<RhythmShape | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [pushState, setPushState] = useState<PushPermission>('default');
  const [pushBusy, setPushBusy] = useState(false);

  const today = useMemo(() => {
    try {
      return getLocalDateStr();
    } catch {
      return new Date().toISOString().slice(0, 10);
    }
  }, []);

  const isCommander = useMemo(
    () =>
      hasCommanderAccess({
        id: operator.id,
        tier: operator.tier ?? undefined,
        role: operator.role,
      }),
    [operator.id, operator.tier, operator.role],
  );

  const fetchToday = useCallback(async () => {
    setLoading(true);
    setError(null);
    try {
      const res = await fetch(
        `/api/daily-ops?date=${today}&operatorId=${encodeURIComponent(operator.id)}&include=rhythm`,
        { credentials: 'include' },
      );
      if (res.status === 402) {
        setError(
          'Daily Ops is a Commander-tier feature. Upgrade to enable Gunny\'s daily schedule planner.',
        );
        setPlan(null);
        return;
      }
      if (!res.ok) {
        setError('Could not load daily ops plan.');
        setPlan(null);
        return;
      }
      const data = await res.json();
      setPlan(data.plan ?? null);
      setRhythm(data.rhythm ?? null);
    } catch (err) {
      console.error('[daily-ops] fetch failed', err);
      setError('Network error loading plan.');
    } finally {
      setLoading(false);
    }
  }, [operator.id, today]);

  const fetchWeek = useCallback(async () => {
    setLoading(true);
    setError(null);
    try {
      const from = dateOffsetISO(-6);
      const to = today;
      const res = await fetch(
        `/api/daily-ops?from=${from}&to=${to}&operatorId=${encodeURIComponent(operator.id)}&include=rhythm`,
        { credentials: 'include' },
      );
      if (res.status === 402) {
        setError(
          'Daily Ops is a Commander-tier feature. Upgrade to enable Gunny\'s daily schedule planner.',
        );
        setWeekPlans([]);
        return;
      }
      if (!res.ok) {
        setError('Could not load week of daily ops plans.');
        setWeekPlans([]);
        return;
      }
      const data = await res.json();
      setWeekPlans(Array.isArray(data.plans) ? data.plans : []);
      setRhythm(data.rhythm ?? null);
    } catch (err) {
      console.error('[daily-ops] week fetch failed', err);
      setError('Network error loading week.');
    } finally {
      setLoading(false);
    }
  }, [operator.id, today]);

  useEffect(() => {
    if (mode === 'today') void fetchToday();
    else void fetchWeek();
  }, [mode, fetchToday, fetchWeek]);

  // Default-on push subscribe.
  useEffect(() => {
    let cancelled = false;
    const init = async () => {
      const state = getPushPermissionState();
      if (cancelled) return;
      setPushState(state);
      if (state === 'unsupported' || state === 'denied') return;
      const result = await ensurePushSubscription({ defaultOn: true });
      if (cancelled) return;
      setPushState(result.state);
    };
    void init();
    return () => {
      cancelled = true;
    };
  }, []);

  const togglePushSubscription = useCallback(async () => {
    setPushBusy(true);
    try {
      if (pushState === 'granted') {
        await unsubscribePush();
        setPushState('default');
      } else {
        const r = await ensurePushSubscription({ defaultOn: true });
        setPushState(r.state);
      }
    } finally {
      setPushBusy(false);
    }
  }, [pushState]);

  const submitFeedback = useCallback(
    async (blockId: string, followed: BlockFeedback['followed']) => {
      if (!plan) return;
      const optimistic: BlockFeedback = {
        followed,
        source: 'tap',
        at: new Date().toISOString(),
      };
      setPlan((prev) =>
        prev ? { ...prev, feedback: { ...prev.feedback, [blockId]: optimistic } } : prev,
      );
      try {
        const res = await fetch('/api/daily-ops', {
          method: 'POST',
          credentials: 'include',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ action: 'feedback', planId: plan.id, blockId, followed }),
        });
        if (!res.ok) await fetchToday();
      } catch {
        await fetchToday();
      }
    },
    [plan, fetchToday],
  );

  const askGunnyForPlan = useCallback(() => {
    if (onSendGunnyMessage) {
      onSendGunnyMessage(
        'Build me today\'s daily ops plan — wake, sun, caffeine window, meals, pre/post workout, wind-down, sleep target. Anchor the workout block to my scheduled session.',
      );
    }
  }, [onSendGunnyMessage]);

  const askGunnyForReshape = useCallback(() => {
    if (onSendGunnyMessage) {
      onSendGunnyMessage('Reshape today\'s daily ops — what would you change?');
    }
  }, [onSendGunnyMessage]);

  // Tier-gate at the UI layer
  if (!isCommander && !operator.isJunior) {
    return (
      <div style={styles.page}>
        <div style={styles.upgradeCard}>
          <h2
            style={{
              color: '#ff8c00',
              fontFamily: 'Orbitron, sans-serif',
              fontSize: 14,
              fontWeight: 700,
              letterSpacing: 2.5,
              margin: 0,
              marginBottom: 8,
            }}
          >
            DAILY OPS — COMMANDER TIER
          </h2>
          <p
            style={{
              color: '#c0c0c0',
              fontSize: 12.5,
              lineHeight: 1.55,
              marginTop: 0,
              marginBottom: 8,
            }}
          >
            {t('daily_ops.upgrade_blurb') ||
              'The Daily Ops Planner is a Commander-tier feature. Gunny generates your full daily schedule — wake, caffeine timing, meal cadence, workout window, wind-down, sleep — fully personalized from the corpus and continuously tuned by your feedback.'}
          </p>
          <p style={{ color: '#666', fontSize: 11, fontStyle: 'italic', margin: 0 }}>
            Operator (Sonnet) tier still gets single-block answers in chat
            (&quot;when should I cut caffeine?&quot;). Commander unlocks the full
            schedule.
          </p>
        </div>
      </div>
    );
  }

  const sortedBlocks = plan ? sortBlocks(plan.blocks) : [];
  const feedbackDisabled =
    !plan ||
    plan.status === 'pending_parent_approval' ||
    plan.status === 'rejected';

  return (
    <div style={mode === 'week' ? styles.pageWide : styles.page}>
      <div style={styles.headerRow}>
        <h1 style={styles.title}>DAILY OPS</h1>

        <div style={styles.segmented}>
          <button
            type="button"
            onClick={() => setMode('today')}
            style={styles.segBtn(mode === 'today')}
          >
            TODAY
          </button>
          <button
            type="button"
            onClick={() => setMode('week')}
            style={styles.segBtn(mode === 'week')}
          >
            WEEK
          </button>
        </div>

        {pushState !== 'unsupported' && (
          <button
            type="button"
            onClick={togglePushSubscription}
            disabled={pushBusy}
            title={
              pushState === 'granted'
                ? 'Notifications on for this device — tap to turn off'
                : pushState === 'denied'
                  ? 'Notifications blocked. Re-enable in your browser settings.'
                  : 'Tap to turn notifications on'
            }
            style={styles.bell(pushState)}
          >
            <span aria-hidden style={{ fontSize: 11 }}>
              {pushState === 'granted' ? '🔔' : pushState === 'denied' ? '🚫' : '🔕'}
            </span>
            {pushState === 'granted'
              ? 'NOTIFY ON'
              : pushState === 'denied'
                ? 'BLOCKED'
                : 'NOTIFY OFF'}
          </button>
        )}

        <span style={styles.dateChip}>{today}</span>
      </div>

      {loading && (
        <div style={{ textAlign: 'center', color: '#666', fontSize: 12, padding: '24px 0' }}>
          Loading…
        </div>
      )}

      {error && !loading && <div style={styles.errorBox}>{error}</div>}

      {/* WEEK MODE */}
      {mode === 'week' && !loading && !error && (
        <>
          {weekPlans.length === 0 ? (
            <div style={styles.emptyCard}>
              <p style={{ marginTop: 0, marginBottom: 12 }}>
                No plans in the last 7 days yet. Ask Gunny to build today&apos;s plan to
                start the rhythm.
              </p>
              <button
                type="button"
                className="btn btn-amber"
                onClick={askGunnyForPlan}
                disabled={!onSendGunnyMessage}
              >
                GENERATE TODAY&apos;S PLAN
              </button>
            </div>
          ) : (
            <>
              <WeekView plans={weekPlans} rhythm={rhythm} todayISO={today} />
              {rhythm && (rhythm.feedbackSampleCount ?? 0) >= 3 && (
                <p style={styles.weekLegend}>
                  Adherence pips: <span style={{ color: '#00ff41' }}>●</span> on time •{' '}
                  <span style={{ color: '#ff8c00' }}>●</span> shifted •{' '}
                  <span style={{ color: '#ff4040' }}>●</span> skipped. Dimmed blocks =
                  often skipped (60%+ skip rate over 14 days).
                </p>
              )}
            </>
          )}
        </>
      )}

      {/* TODAY MODE */}
      {mode === 'today' && !loading && !plan && !error && (
        <div style={styles.emptyCard}>
          <p style={{ marginTop: 0, marginBottom: 12 }}>
            No plan for today yet. Ask Gunny to build one.
          </p>
          <button
            type="button"
            className="btn btn-amber"
            onClick={askGunnyForPlan}
            disabled={!onSendGunnyMessage}
          >
            GENERATE TODAY&apos;S PLAN
          </button>
        </div>
      )}

      {mode === 'today' && plan && (
        <>
          <div style={styles.statusRow}>
            <span>
              STATUS:{' '}
              <span style={{ color: STATUS_COLOR[plan.status] }}>
                {STATUS_COPY[plan.status]}
              </span>
            </span>
            <button
              type="button"
              onClick={askGunnyForReshape}
              disabled={!onSendGunnyMessage}
              style={styles.reshapeLink}
            >
              ASK GUNNY TO RESHAPE
            </button>
          </div>

          {plan.notes && <div style={styles.notesCallout}>{plan.notes}</div>}

          {plan.status === 'pending_parent_approval' && (
            <div style={styles.juniorPending}>
              <strong>Awaiting parent approval.</strong> Your parent will review this
              plan before it goes live. You can&apos;t mark blocks complete yet.
            </div>
          )}
          {plan.status === 'rejected' && plan.rejectionNotes && (
            <div style={styles.juniorRejected}>
              <strong>Plan rejected.</strong> {plan.rejectionNotes}
            </div>
          )}

          <div>
            {sortedBlocks.map((b) => (
              <BlockCard
                key={b.id}
                block={b}
                feedback={plan.feedback?.[b.id]}
                onFeedback={(followed) => submitFeedback(b.id, followed)}
                disabled={feedbackDisabled}
                skipRate={rhythm?.blockSkipRates?.[b.category]}
              />
            ))}
          </div>

          <div style={styles.footer}>
            <p style={styles.footerNote}>
              Plan generated by Gunny on {new Date(plan.generatedAt).toLocaleString()}.
            </p>
            <button
              type="button"
              className="btn btn-ghost"
              onClick={askGunnyForPlan}
              disabled={!onSendGunnyMessage}
            >
              REGENERATE
            </button>
          </div>
        </>
      )}
    </div>
  );
};

export default DailyOps;
