'use client';

// Daily Ops — Gunny's prescribed daily-schedule planner.
//
// Sister surface to the Workout Planner. Owns the rhythm of the day —
// wake / sun / caffeine / meals / supps / workout window / wind-down /
// sleep — fully personalized using corpus knowledge (hypertrophy
// supplement stack, natural T optimization protocol, periodization
// phase, junior policies, life stage). Plans are generated by Gunny
// via the `<daily_ops_json>` channel — this surface is read-only +
// feedback, NOT a builder. Tap "Generate today's plan" → routes to
// Gunny chat with a pre-filled prompt.
//
// Tier-gated to Commander (opus / white_glove). For juniors, gating
// is delegated to the parent's tier — ParentDashboard surfaces
// pending plans for parent approval before they go live for the
// junior.

import React, { useEffect, useMemo, useState, useCallback } from 'react';
import { useLanguage } from '@/lib/i18n';
import { Operator } from '@/lib/types';
import { hasCommanderAccess } from '@/lib/tierGates';
import { getLocalDateStr } from '@/lib/dateUtils';
import * as Icon from '@/components/Icons';
import type {
  DailyOpsPlanShape,
  DailyBlock,
  BlockCategory,
  BlockFeedback,
} from '@/lib/dailyOpsTypes';

interface DailyOpsProps {
  operator: Operator;
  /** Bridge to GunnyChat — opens the chat panel and primes a prompt. */
  onSendGunnyMessage?: (prompt: string) => void;
}

// ---------------------------------------------------------------------------
// Visual taxonomy — icon + accent color per block category.
// Keeps the timeline scannable at a glance: meals are amber, sleep is
// indigo, recovery is teal, etc. Falls back to a neutral default for
// unknown categories so a forward-compat block doesn't crash the UI.
// ---------------------------------------------------------------------------

const CATEGORY_META: Record<
  BlockCategory,
  { label: string; tint: string; ring: string }
> = {
  wake:                  { label: 'WAKE',         tint: 'text-yellow-300',   ring: 'ring-yellow-500/30' },
  sun_exposure:          { label: 'SUN',          tint: 'text-yellow-200',   ring: 'ring-yellow-300/30' },
  caffeine_window_open:  { label: 'CAFFEINE',     tint: 'text-orange-300',   ring: 'ring-orange-500/30' },
  caffeine_cutoff:       { label: 'CAFF CUTOFF',  tint: 'text-orange-300',   ring: 'ring-orange-500/30' },
  meal:                  { label: 'MEAL',         tint: 'text-amber-300',    ring: 'ring-amber-500/30' },
  pre_workout_supp:      { label: 'PRE-WO SUPP',  tint: 'text-emerald-300',  ring: 'ring-emerald-500/30' },
  workout:               { label: 'WORKOUT',      tint: 'text-red-400',      ring: 'ring-red-500/40' },
  post_workout:          { label: 'POST-WO',      tint: 'text-emerald-300',  ring: 'ring-emerald-500/30' },
  mobility:              { label: 'MOBILITY',     tint: 'text-cyan-300',     ring: 'ring-cyan-500/30' },
  wind_down:             { label: 'WIND DOWN',    tint: 'text-purple-300',   ring: 'ring-purple-500/30' },
  pre_bed_supp:          { label: 'PRE-BED SUPP', tint: 'text-purple-300',   ring: 'ring-purple-500/30' },
  sleep_target:          { label: 'SLEEP',        tint: 'text-indigo-300',   ring: 'ring-indigo-500/40' },
  sauna:                 { label: 'SAUNA',        tint: 'text-rose-300',     ring: 'ring-rose-500/30' },
  cold_exposure:         { label: 'COLD',         tint: 'text-sky-300',      ring: 'ring-sky-500/30' },
  recovery_walk:         { label: 'WALK',         tint: 'text-teal-300',     ring: 'ring-teal-500/30' },
  fifa_warmup:           { label: 'FIFA 11+',     tint: 'text-emerald-300',  ring: 'ring-emerald-500/30' },
  mistake_reset_ritual:  { label: 'RESET',        tint: 'text-fuchsia-300',  ring: 'ring-fuchsia-500/30' },
};

const META_FALLBACK = { label: 'BLOCK', tint: 'text-neutral-300', ring: 'ring-neutral-500/30' };

function blockMeta(c: BlockCategory) {
  return CATEGORY_META[c] ?? META_FALLBACK;
}

function sortBlocks(blocks: DailyBlock[]): DailyBlock[] {
  return [...blocks].sort((a, b) => a.startTime.localeCompare(b.startTime));
}

const STATUS_COPY: Record<DailyOpsPlanShape['status'], string> = {
  active: 'ACTIVE',
  pending_parent_approval: 'AWAITING PARENT APPROVAL',
  approved: 'APPROVED',
  rejected: 'REJECTED — REQUEST A NEW PLAN',
};

// ---------------------------------------------------------------------------
// Block card — vertical timeline row with 3-tap feedback.
// ---------------------------------------------------------------------------

interface BlockCardProps {
  block: DailyBlock;
  feedback: BlockFeedback | undefined;
  onFeedback: (followed: BlockFeedback['followed']) => void;
  disabled: boolean;
}

const BlockCard: React.FC<BlockCardProps> = ({ block, feedback, onFeedback, disabled }) => {
  const meta = blockMeta(block.category);
  const followed = feedback?.followed;

  return (
    <div className={`flex gap-3 py-3 border-l-2 pl-3 ${meta.ring}`}>
      <div className="flex-shrink-0 w-16">
        <div className="text-sm font-mono text-neutral-100">{block.startTime}</div>
        {block.endTime && (
          <div className="text-xs font-mono text-neutral-500">→ {block.endTime}</div>
        )}
      </div>
      <div className="flex-1 min-w-0">
        <div className="flex items-center gap-2 mb-0.5">
          <span className={`text-[10px] font-bold tracking-wider ${meta.tint}`}>
            {meta.label}
          </span>
          {block.flexibility !== 'fixed' && (
            <span className="text-[9px] text-neutral-500 font-mono">
              ±{block.flexibility === 'flex_30' ? '30m' : '2h'}
            </span>
          )}
        </div>
        <div className="text-sm text-neutral-100 font-medium">{block.label}</div>
        <div className="text-xs text-neutral-400 mt-0.5 italic leading-snug">
          {block.rationale}
        </div>
        {!disabled && (
          <div className="flex gap-1.5 mt-2">
            <button
              type="button"
              onClick={() => onFeedback('yes')}
              className={`px-2 py-0.5 text-[10px] font-bold rounded border transition-colors ${
                followed === 'yes'
                  ? 'bg-emerald-600/30 border-emerald-500 text-emerald-100'
                  : 'border-neutral-700 text-neutral-400 hover:border-emerald-600 hover:text-emerald-300'
              }`}
            >
              ✓ ON TIME
            </button>
            <button
              type="button"
              onClick={() => onFeedback('partial')}
              className={`px-2 py-0.5 text-[10px] font-bold rounded border transition-colors ${
                followed === 'partial'
                  ? 'bg-amber-600/30 border-amber-500 text-amber-100'
                  : 'border-neutral-700 text-neutral-400 hover:border-amber-600 hover:text-amber-300'
              }`}
            >
              ~ SHIFTED
            </button>
            <button
              type="button"
              onClick={() => onFeedback('no')}
              className={`px-2 py-0.5 text-[10px] font-bold rounded border transition-colors ${
                followed === 'no'
                  ? 'bg-rose-600/30 border-rose-500 text-rose-100'
                  : 'border-neutral-700 text-neutral-400 hover:border-rose-600 hover:text-rose-300'
              }`}
            >
              ✗ SKIPPED
            </button>
          </div>
        )}
      </div>
    </div>
  );
};

// ---------------------------------------------------------------------------
// Main DailyOps surface
// ---------------------------------------------------------------------------

const DailyOps: React.FC<DailyOpsProps> = ({ operator, onSendGunnyMessage }) => {
  const { t } = useLanguage();
  const [plan, setPlan] = useState<DailyOpsPlanShape | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  // Today in local time. dateUtils.getLocalDateStr() already returns
  // the device-local YYYY-MM-DD which is what the planner uses for its
  // own slot keys, so we mirror that here for consistency.
  const today = useMemo(() => {
    try {
      return getLocalDateStr();
    } catch {
      return new Date().toISOString().slice(0, 10);
    }
  }, []);

  const isCommander = useMemo(
    () =>
      hasCommanderAccess({
        id: operator.id,
        tier: operator.tier ?? undefined,
        role: operator.role,
      }),
    [operator.id, operator.tier, operator.role],
  );

  // For juniors: gating depends on parent tier, not the junior's own.
  // The server enforces this; the UI tells juniors "ask your parent" if
  // there's no parent on file at Commander tier. We don't fetch the
  // parents here — we just trust the server's 200 vs 4xx response. If
  // the server returns 403 we surface the upgrade message.
  const fetchPlan = useCallback(async () => {
    setLoading(true);
    setError(null);
    try {
      const res = await fetch(
        `/api/daily-ops?date=${today}&operatorId=${encodeURIComponent(operator.id)}`,
        { credentials: 'include' },
      );
      if (res.status === 402) {
        setError('Daily Ops is a Commander-tier feature. Upgrade to enable Gunny\'s daily schedule planner.');
        setPlan(null);
        return;
      }
      if (!res.ok) {
        setError('Could not load daily ops plan.');
        setPlan(null);
        return;
      }
      const data = await res.json();
      setPlan(data.plan ?? null);
    } catch (err) {
      console.error('[daily-ops] fetch failed', err);
      setError('Network error loading plan.');
    } finally {
      setLoading(false);
    }
  }, [operator.id, today]);

  useEffect(() => {
    void fetchPlan();
  }, [fetchPlan]);

  const submitFeedback = useCallback(
    async (blockId: string, followed: BlockFeedback['followed']) => {
      if (!plan) return;
      // Optimistic update
      const optimistic: BlockFeedback = {
        followed,
        source: 'tap',
        at: new Date().toISOString(),
      };
      setPlan((prev) =>
        prev ? { ...prev, feedback: { ...prev.feedback, [blockId]: optimistic } } : prev,
      );

      try {
        const res = await fetch('/api/daily-ops', {
          method: 'POST',
          credentials: 'include',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ action: 'feedback', planId: plan.id, blockId, followed }),
        });
        if (!res.ok) {
          // Roll back optimistic update on failure.
          await fetchPlan();
        }
      } catch {
        await fetchPlan();
      }
    },
    [plan, fetchPlan],
  );

  const askGunnyForPlan = useCallback(() => {
    if (onSendGunnyMessage) {
      onSendGunnyMessage(
        'Build me today\'s daily ops plan — wake, sun, caffeine window, meals, pre/post workout, wind-down, sleep target. Anchor the workout block to my scheduled session.',
      );
    }
  }, [onSendGunnyMessage]);

  const askGunnyForReshape = useCallback(() => {
    if (onSendGunnyMessage) {
      onSendGunnyMessage('Reshape today\'s daily ops — what would you change?');
    }
  }, [onSendGunnyMessage]);

  // ── Tier-gate at the UI layer (server is source of truth) ───────────
  if (!isCommander && !operator.isJunior) {
    return (
      <div className="p-6 max-w-2xl mx-auto">
        <div className="border border-amber-700/40 bg-amber-950/20 rounded-lg p-5">
          <div className="flex items-center gap-2 mb-2">
            <Icon.Clock size={18} className="text-amber-300" />
            <h2 className="text-amber-300 font-bold tracking-wider">DAILY OPS — COMMANDER TIER</h2>
          </div>
          <p className="text-sm text-neutral-300 leading-relaxed mb-2">
            {t('daily_ops.upgrade_blurb') ||
              'The Daily Ops Planner is a Commander-tier feature. Gunny generates your full daily schedule — wake, caffeine timing, meal cadence, workout window, wind-down, sleep — fully personalized from the corpus and continuously tuned by your feedback.'}
          </p>
          <p className="text-xs text-neutral-500 italic">
            Operator (Sonnet) tier still gets single-block answers in chat ("when should I cut caffeine?"). Commander unlocks the full schedule.
          </p>
        </div>
      </div>
    );
  }

  // ── Render ──────────────────────────────────────────────────────────

  const sortedBlocks = plan ? sortBlocks(plan.blocks) : [];
  const feedbackDisabled =
    !plan ||
    plan.status === 'pending_parent_approval' ||
    plan.status === 'rejected';

  return (
    <div className="p-4 max-w-2xl mx-auto">
      <div className="flex items-center justify-between mb-4">
        <div className="flex items-center gap-2">
          <Icon.Clock size={20} className="text-amber-300" />
          <h1 className="text-amber-300 font-bold tracking-wider text-lg">
            {t('daily_ops.title') || 'DAILY OPS'}
          </h1>
        </div>
        <div className="text-xs text-neutral-400 font-mono">{today}</div>
      </div>

      {loading && (
        <div className="text-center text-neutral-500 text-sm py-8">Loading plan…</div>
      )}

      {error && !loading && (
        <div className="border border-rose-700/40 bg-rose-950/20 rounded p-3 text-sm text-rose-200 mb-4">
          {error}
        </div>
      )}

      {!loading && !plan && !error && (
        <div className="border border-neutral-800 bg-neutral-900/40 rounded-lg p-5 text-center">
          <p className="text-sm text-neutral-300 mb-3">
            No plan for today yet. Ask Gunny to build one.
          </p>
          <button
            type="button"
            onClick={askGunnyForPlan}
            disabled={!onSendGunnyMessage}
            className="px-4 py-2 bg-amber-600 hover:bg-amber-500 disabled:bg-neutral-700 disabled:text-neutral-500 text-neutral-950 font-bold tracking-wider text-sm rounded transition-colors"
          >
            GENERATE TODAY&apos;S PLAN
          </button>
        </div>
      )}

      {plan && (
        <>
          {/* Status banner */}
          <div className="mb-3 flex items-center justify-between">
            <div className="text-[10px] font-bold tracking-widest text-neutral-400">
              STATUS:{' '}
              <span
                className={
                  plan.status === 'active' || plan.status === 'approved'
                    ? 'text-emerald-300'
                    : plan.status === 'pending_parent_approval'
                      ? 'text-amber-300'
                      : 'text-rose-300'
                }
              >
                {STATUS_COPY[plan.status]}
              </span>
            </div>
            <button
              type="button"
              onClick={askGunnyForReshape}
              disabled={!onSendGunnyMessage}
              className="text-[10px] font-bold tracking-wider text-neutral-400 hover:text-amber-300 underline-offset-2 hover:underline disabled:text-neutral-600 disabled:hover:no-underline"
            >
              ASK GUNNY TO RESHAPE
            </button>
          </div>

          {/* Day-level rationale */}
          {plan.notes && (
            <div className="mb-4 px-3 py-2 border-l-2 border-amber-700/40 bg-amber-950/10 text-xs text-amber-200/80 italic">
              {plan.notes}
            </div>
          )}

          {/* Junior-pending banner */}
          {plan.status === 'pending_parent_approval' && (
            <div className="mb-4 border border-amber-700/40 bg-amber-950/20 rounded p-3 text-xs text-amber-200">
              <strong>Awaiting parent approval.</strong> Your parent will review this plan
              before it goes live. You can&apos;t mark blocks complete yet.
            </div>
          )}
          {plan.status === 'rejected' && plan.rejectionNotes && (
            <div className="mb-4 border border-rose-700/40 bg-rose-950/20 rounded p-3 text-xs text-rose-200">
              <strong>Plan rejected.</strong> {plan.rejectionNotes}
            </div>
          )}

          {/* Timeline */}
          <div className="space-y-1">
            {sortedBlocks.map((b) => (
              <BlockCard
                key={b.id}
                block={b}
                feedback={plan.feedback?.[b.id]}
                onFeedback={(followed) => submitFeedback(b.id, followed)}
                disabled={feedbackDisabled}
              />
            ))}
          </div>

          {/* Regenerate footer */}
          <div className="mt-6 pt-4 border-t border-neutral-800 flex flex-col gap-2 items-center">
            <p className="text-[11px] text-neutral-500 italic">
              Plan generated by Gunny on{' '}
              {new Date(plan.generatedAt).toLocaleString()}.
            </p>
            <button
              type="button"
              onClick={askGunnyForPlan}
              disabled={!onSendGunnyMessage}
              className="px-3 py-1 text-[11px] font-bold tracking-wider text-neutral-400 hover:text-amber-300 border border-neutral-800 hover:border-amber-700 rounded transition-colors disabled:text-neutral-600 disabled:hover:no-underline"
            >
              REGENERATE
            </button>
          </div>
        </>
      )}
    </div>
  );
};

export default DailyOps;
