// @vitest-environment node
import { describe, it, expect } from 'vitest';
import { readdirSync, readFileSync, statSync } from 'node:fs';
import { join, relative } from 'node:path';

/**
 * Emoji guard — the UI is deliberately monochrome/tactical and uses the SVG
 * set in src/components/Icons.tsx instead of emoji. This test fails if any
 * emoji (or emoji-style dingbat/symbol such as check / cross / warning / bolt /
 * star glyphs) creeps back
 * into the source under src/. Use an <Icon.* /> component (or plain text like
 * [DONE] / "Warning:" for strings sent to the LLM) instead.
 *
 * NOT flagged: typographic arrows (→ ← ↻, U+2190–21FF) and geometric carets /
 * bullets (▼ ▶ ▲ ●, U+25A0–25FF) — these are plain UI glyphs, not emoji.
 */
const EMOJI = /[\u{1F000}-\u{1FAFF}\u{2600}-\u{27BF}\u{2B00}-\u{2BFF}\u{FE00}-\u{FE0F}\u{1F1E6}-\u{1F1FF}]/u;

const ROOT = join(__dirname, '..', '..'); // → src/
// 'generated' holds Prisma's codegen output (emoji in its banner comments) —
// it's regenerated by `prisma generate`, not hand-edited, so it's out of scope.
const SKIP_DIRS = new Set(['node_modules', '.next', 'dist', '.git', 'generated']);

function walk(dir: string, out: string[] = []): string[] {
  for (const name of readdirSync(dir)) {
    if (SKIP_DIRS.has(name)) continue;
    const full = join(dir, name);
    const st = statSync(full);
    if (st.isDirectory()) walk(full, out);
    else if (/\.(ts|tsx)$/.test(name)) out.push(full);
  }
  return out;
}

describe('no emoji in source', () => {
  it('src/ is free of emoji (use Icons.tsx / plain text instead)', () => {
    const offenders: string[] = [];
    for (const file of walk(ROOT)) {
      const lines = readFileSync(file, 'utf8').split('\n');
      lines.forEach((line, i) => {
        const m = line.match(EMOJI);
        if (m) offenders.push(`${relative(ROOT, file)}:${i + 1}  ${m[0]}  ${line.trim().slice(0, 80)}`);
      });
    }
    expect(offenders, `Emoji found — replace with an <Icon.* /> or plain text:\n${offenders.join('\n')}`).toEqual([]);
  });
});
